### ISSUE TITLE
Support more conventional iteration over blocks

### ISSUE THREAD

**Issue by jonrkarr** [ASinanSaglam/PyBioNetGen#11]
This package currently enables iteration over blocks like this:
```python
model = bionetgen.bngmodel(filename)
for id, config in model.parameters.items.items():
    pass
```

More conventional iteration would work like this (i.e., enable the items method directly over each block)
```python
model = bionetgen.bngmodel(filename)
for id, config in model.parameters.items():
    pass
```

**Comment by ASinanSaglam** [comment]
Each block has their python internals overwritten in a way to allow for iteration without the need to use any attributes. Some very basic documentation is [here](https://pybionetgen.readthedocs.io/en/latest/bngmodel.html#blocks). 

E.g.
```
for parameter in model.parameters:
    print(parameter)
```

Each object has different properties that can be manipulated. I intend to make them more intuitive and further document it down the line.

**Comment by jonrkarr** [comment]
I expected the regular dict methods because the blocks print out as OrderedDicts. They're not actually ordered dicts, but this depiction crates an expectation that they will behave similarly.
```
model.parameters
Out[23]: OrderedDict([('k_1', k_1 0), ('r_2', r_2 0), ('g0', g0 4), ('g1', g1 18), ('k', k 1), ('ha', ha 1e-5), ('hr', hr 0.1), ('fa', fa 1e-5), ('fr', fr 1)])
```

**Comment by ASinanSaglam** [comment]
Hmm, true, I will update __repr__ for blocks to clarify that they are not OrderedDicts. Not sure what it will print exactly but it will clarify that it's not an OrderedDict at least.

**Comment by jonrkarr** [comment]
One of a couple of things would make sense to me 
- The data type
- A human-readable list of the elements in the block

Alternatively, you could make each block behave more like a ordered dict by defining the other dict methods.

**Comment by ASinanSaglam** [comment]
I changed it so that it prints `X block with Y elements: Z` where X is the block name, Y is the number of elements and Z is a list of items in the block. There is some question whether if I should print something different each element in some blocks (e.g. for each rule it prints the _name_ of the rule which is not what everyone things of when they thing of a particular rule) but this should avoid the issue for now.

**Comment by ASinanSaglam** [comment]
I'll close this for now, please let me know if you have any improvement suggestions on this. I think it could be improved but at least it addresses the issue.
