### ISSUE TITLE
Errors in reading BNGL files should be reported consistently

### ISSUE THREAD

**Issue by jonrkarr** [ASinanSaglam/PyBioNetGen#4]
`bionetgen.bngmodel` raises errors for some problems, but prints messages to stdout for others. It would be helpful for errors to be reported in a consistent way.

Example:
https://github.com/ASinanSaglam/PyBioNetGen/blob/378d1d639efaa96c2be2f2a11c646e7a5328b379/bionetgen/xmlapi/bngparser.py#L59

Could be replaced with the following to be consistent with the report of other errors
```python
raise ValueError("XML file couldn't be generated")
```

**Comment by ASinanSaglam** [comment]
Added more error raising. Along with #5 and #6, this will likely be an ongoing effort.
