### ISSUE TITLE
Enable issues for RuleWorld/PyBioNetGen

### ISSUE THREAD

**Issue by jonrkarr** [ASinanSaglam/PyBioNetGen#9]
I posted issues here because issues are not enabled for https://github.com/RuleWorld/PyBioNetGen. Enabling issues at https://github.com/RuleWorld/PyBioNetGen would encourage people to post issues there.

**Comment by ASinanSaglam** [comment]
Didn't realize that was the case, I guess it's because it's under another username. It's enabled now.
